### PR TITLE
Simplify address finding

### PR DESCRIPTION
**Pull request by PuZZleDucK**
also added state tag which is why I think it's not auto-merging

### CODE REVIEW

**Comment by equivalentideas** [comment]
Thanks for this @PuZZleDucK :star2: Could you just describe for me here how this actually changes the addresses? e.g. a before and after

**Comment by PuZZleDucK** [comment]
NP... Just let me remember what I was doing :p ...

There is a line of data with the address and description mashed together. A good example is "Material Change of Use for Forestry at 8314 Ayr Dalbeg Road, Dalbeg"

Previously I was searching for the last number (8314 in our example) and taking it and the rest of the line as the address.

However this breaks when there is no number in the address (this recent example was crashing the scraper: "Material Change of Use - Solar Farm at Ayr Dalbeg Road, Mulgrave") and in other cases.

So far the description and address are always mashed together with " at ", so I've switched to using that.

**Comment by PuZZleDucK** [comment]
... oh and then I thought I'd be really smart and add the state tag :o

**Comment by equivalentideas** [comment]
Thanks heaps @PuZZleDucK I've checked this works and I'll merge this. Thanks for making this scraper better :star2: There's some interesting DAs in there.

**Pull request merged**
